import type { TippoOptions } from "./tippo/tippo";

export const TIPS: Array<TippoOptions> = [
  {
    tippoId: "tippo_0",
    content: "Hello, this is a tippo tool tip!",
    arrowPos: 1,
    side: "above",
    targetPos: 2,
  },
  {
    tippoId: "tippo_1",
    content: "This tool tip pops up below!",
    arrowPos: 1,
    side: "below",
    targetPos: 3,
    animation: "grow",
  },
  {
    tippoId: "tippo_2",
    content: "Other cool tippo information",
    arrowPos: 1,
    side: "above",
    targetPos: 3,
    animationEntry: "pop-away",
    buttonContent: "Got it",
  },
  {
    tippoId: "tippo_3",
    content: "Other cool tippo information",
    arrowPos: 1,
    side: "above",
    targetPos: 3,
    animation: "grow",
    animationEntry: "fade",
    buttonContent: "Got it",
  },
  {
    tippoId: "tippo_4",
    content: "Other cool tippo information",
    arrowPos: 1,
    side: "above",
    targetPos: 3,
    animation: "grow",
    animationEntry: "pop-away",
    buttonContent: "Got it",
  },
  {
    tippoId: "tippo_5",
    content: "Other cool tippo information",
    arrowPos: 1,
    side: "above",
    targetPos: 3,
    animation: "grow",
    animationEntry: "pop-away",
    buttonContent: "Got it",
  },
  {
    tippoId: "tippo_6",
    content: "Other cool tippo information",
    arrowPos: 1,
    side: "above",
    targetPos: 3,
    animation: "grow",
    animationEntry: "pop-away",
    buttonContent: "Got it",
  },
];
